---
kind: pipeline
type: docker
name: CI/CD

steps:
  - name: test
    image: golang:1.16
    commands:
      - make test

  - name: build
    image: golang
    commands:
      - make build

  - name: lint
    image: golangci/golangci-lint
    commands:
      - make lint
