---
kind: pipeline
type: docker
name: CI/CD

steps:
  - name: test
    image: golang:1.16-alpine
    commands:
      - go test ./...

  - name: build
    image: golang
    environment:
      - CGO_ENABLED=0
    commands:
      - go build ./...

  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --fast
